# Generated by Django 4.2.4 on 2023-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100)),
                ('order_created_date', models.DateTimeField(auto_now_add=True)),
                ('order_delivered_date', models.DateTimeField(blank=True, null=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery'), ('invoice', 'Invoice')], max_length=20)),
            ],
        ),
    ]
